language: generic

sudo: required

# Only run test when committing to a master branch.
branches:
  only:
    - master

env:
  globaL:
    - COMPOSE_HTTP_TIMEOUT=3600
    - AEGIR_TESTS_VERSION=refactor-entrypoint

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:
  # upgrade docker-engine to specific version
  - git clone http://github.com/aegir-project/tests.git
  - cd tests
  - git checkout $AEGIR_TESTS_VERSION
  - sudo bash travis/prepare-docker.sh

  - sudo mkdir vendor
  - sudo chmod 777 vendor

  - sudo mkdir bin
  - sudo chmod 777 bin

  - cd ..

  # First build stock image.
  - sudo docker build --rm -t aegir/hostmaster .

  # Then build local image. Only difference is UID defaults to 1000
  - sudo docker build --rm -t aegir/hostmaster:local -f Dockerfile-local .

  # Then build test image. Only difference is CMD defaults to run-tests.sh
  - sudo docker build --rm -t aegir/hostmaster:test -f Dockerfile-test .

  # Go to tests/travis folder. Docker-compose files are in there.
  - cd tests/travis
script:

  # Launch docker-compose.yml file within tests repo.
  # Use SG so that we don't have to use sudo. This is so the local user UID and the docker container UID match.
  - sg - docker -c 'docker-compose run hostmaster --rm'
